import os
import re

import models

def load(gml_file_name):
    gml_file_path = os.path.abspath(gml_file_name)
    print('open gml file name :',gml_file_name)
    with open(gml_file_path,'r',encoding="utf_8") as f:
        graph = parse_attributes(f)
    return graph

def dump(dump_file_name, graph):
    dump_file_path = os.path.abspath(dump_file_name)
    print('dump file name :',dump_file_path)
    with open(dump_file_path,'w',encoding="utf_8") as f:
        serialize_graph(f, graph)

def parse_attributes(gml_file):
    data_types = {'node', 'edge', 'hyper_edge'}
    is_in_block = False
    element_list = []

    graph = models.Graph()

    nodes = []
    edges = []
    variables = []
    pending_edges = []
    pending_variables = []

    while True:
        line = gml_file.readline()
        if line:
            split_data = line.split()
            if not split_data:
                continue
            head = split_data[0]
            if head in data_types:
                is_in_block = True
                elements = ""
                element_list = []
                data_type = head
            if is_in_block:
                element_list.extend(split_data)
                if ']' in split_data:
                    is_in_block = False
                    element_str = "".join(f"{s} " for s in element_list)

                    match data_type:
                        case "node":
                            nodes.append(process_node(element_str))
                        case "edge":
                            pending_edges.append(parse_edge(element_str))
                        case "hyper_edge":
                            hyper_edge_node, hyper_edge_edges, hyper_edge_variable = parse_hyper_edge(element_str)
                            nodes.append(hyper_edge_node)
                            pending_edges.extend(hyper_edge_edges)
                            pending_variables.append(hyper_edge_variable)
        else:
            break
    node_dict = {n.node_id: n for n in nodes}
    edges = process_edge(node_dict, pending_edges)
    variables = process_variable(node_dict, pending_variables)

    graph.nodes = node_dict
    graph.edges = edges
    graph.variables = variables
    graph.bind_count = len(variables)

    return graph

def serialize_graph(dump_file, graph):
    variable_node_ids = []
    variable_edge_ids = {}
    tab = '    '
    dump_file.write(f'Graph [\n{tab}comment "Generated by Twig - Layout Engine"\n{tab}directed 1\n\n')
    for node in graph.nodes.values():
        if not node.is_variable:
            write_data = f'{tab}node [ id {node.node_id} label "{node.label}" ]\n'
            dump_file.write(write_data)
        else:
            variable_node_ids.append(node.node_id)
    dump_file.write('\n')
    for edge in graph.edges.values():
        src_id = edge.source.node_id
        tgt_id = edge.target.node_id

        src_is_var = src_id in variable_node_ids
        tgt_is_var = tgt_id in variable_node_ids

        if not src_is_var and not tgt_is_var:
            write_data = f'{tab}edge [ id {edge.edge_id} source {edge.source.node_id} target {edge.target.node_id} label "{edge.label}" ]\n'
            dump_file.write(write_data)
        elif src_is_var and not tgt_is_var:
            variable_edge_ids.setdefault(int(src_id), {})[int(tgt_id)] = int(edge.edge_id)
        else:
            variable_edge_ids.setdefault(int(tgt_id), {})[int(src_id)] = int(edge.edge_id)
    dump_file.write('\n')
    for variable in graph.variables.values():
        node = graph.nodes.get(variable.variable_node_id)
        variable_datas = variable_edge_ids.get(variable.variable_node_id)
        edge_id_text = ''
        target_text = ''
        for target in variable.abstracted_nodes:
            edge_id_text += f'{variable_datas.get(target.node_id)},'
            target_text += f'{target.node_id},'
        edge_id_text = edge_id_text[:-1]
        target_text = target_text[:-1]

        write_data = f'{tab}hyper_edge [ node_id {node.node_id} edge_id [{edge_id_text}] label "{node.label}" target [{target_text}] ]\n'
        dump_file.write(write_data)
    dump_file.write(']')


def process_node(element_str):
    node = models.Node()
    node_element = {'id', 'label'}
    is_next_value = False
    element_name = ""

    pattern = r'("[^"]*"|\S+)'
    items = re.findall(pattern, element_str)
    for item in items:
        if is_next_value:
            is_next_value = False
            match element_name:
                case 'id':
                    node.node_id = int(item)
                case 'label':
                    item = item[1:-1]
                    node.label = item
        if item in node_element:
            is_next_value = True
            element_name = item
    return node

def parse_edge(element_str):
    pending_edge = models.PendingEdge()
    edge_element = {'id', 'label', 'source', 'target'}
    is_next_value = False
    element_name = ""

    pattern = r'("[^"]*"|\S+)'
    items = re.findall(pattern, element_str)
    for item in items:
        if is_next_value:
            is_next_value = False
            match element_name:
                case 'id':
                    pending_edge.edge_id = int(item)
                case 'label':
                    item = item[1:-1]
                    pending_edge.label = item
                case 'source':
                    pending_edge.source = int(item)
                case 'target':
                    pending_edge.target = int(item)
        if item in edge_element:
            is_next_value = True
            element_name = item
    return pending_edge

def parse_hyper_edge(element_str):
    node = models.Node()
    pending_variable = models.PendingVariable()
    hyper_edge_element = {'node_id', 'edge_id', 'label', 'target'}
    is_next_value = False
    element_name = ""

    pending_edge_source = 0
    pending_edge_label  = ""
    pending_edge_ids     = []
    pending_edge_targets = []

    pending_edges = []

    pattern = r'("[^"]*"|\S+)'
    items = re.findall(pattern, element_str)
    for item in items:
        if is_next_value:
            is_next_value = False
            match element_name:
                case 'node_id':
                    node.node_id = int(item)
                    node.is_variable = True
                    pending_variable.variable_node_id = int(item)
                    pending_edge_source = int(item)
                case 'edge_id':
                    item = item[1:-1]
                    pending_edge_ids = item.split(",")
                case 'label':
                    item = item[1:-1]
                    node.label = item
                    pending_edge_label = item
                case 'target':
                    item = item[1:-1]
                    pending_variable.abstracted_nodes = item.split(",")
                    pending_edge_targets = item.split(",")
        if item in hyper_edge_element:
            is_next_value = True
            element_name = item
    for edge_id, target in zip(pending_edge_ids, pending_edge_targets):
        pending_edge = models.PendingEdge()
        pending_edge.edge_id = edge_id
        pending_edge.label   = pending_edge_label
        pending_edge.source  = int(pending_edge_source)
        pending_edge.target = int(target)
        pending_edges.append(pending_edge)
    return node, pending_edges, pending_variable

def process_edge(node_dict, pending_edges):
    edges = {}
    for pending in pending_edges:
        edge = models.Edge()
        edge.edge_id = pending.edge_id
        edge.label   = pending.label
        edges[edge.edge_id] = edge
    for pending,  edge in zip(pending_edges, edges.values()):
        edge.source  = node_dict.get(pending.source)
        edge.target  = node_dict.get(pending.target)
    return edges

def process_variable(node_dict, pending_variables):
    variables = {}
    for pending in pending_variables:
        variable = models.Variable()
        nodes = []
        variable.variable_node_id = pending.variable_node_id
        variables[variable.variable_node_id] = variable
    for pending, variable in zip(pending_variables, variables.values()):
        vas = []
        for pa, va in zip(pending.abstracted_nodes, variable.abstracted_nodes):
            vas.append(node_dict.get(int(pa)))
        variable.abstracted_nodes = vas
    return variables